import type {
  BionicConfig,
  BionicRatios,
  MutationConfig,
  ProcessorConfig,
  SyllablePatterns,
} from "../types";

import { ElementCheckType } from "../types";

export const isMobile = /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
export const pixelRatio = window.devicePixelRatio || 1;
export const screenWidth = window.innerWidth;
export const screenHeight = window.innerHeight;

const MUTATION: MutationConfig = {
  DEBOUNCE_DELAY: 100,
  OPTIONS: {
    attributeOldValue: false,
    attributes: false,
    characterData: true,
    characterDataOldValue: true,
    childList: true,
    subtree: true,
  },
} as const;

const BIONIC_RATIOS: BionicRatios = {
  COMMON_WORDS: 0.35,
  MULTI_SYLLABLE: {
    FOUR_PLUS: 0.65,
    THREE: 0.55,
    TWO: 0.45,
  },
  SINGLE_SYLLABLE: {
    _SHORT: 0.35,
    LONG: 0.45,
    MEDIUM: 0.4,
  },
} as const;

const BIONIC_SYLLABLE_PATTERNS: SyllablePatterns = {
  ADD: /(?:ia|riet|dien|iu|io|ii|[aeiouy]ing|[^aeiouy]ying$|ui[aeiouy]|eo|[aeiou]{2}|[aeiou]y[aeiou]|[aeiou](?:le|les|ed|es|est|eth|ist|ism|ize|ous|ship|tion|tive|ture|ure|ward|wise|yer|ying)$)/g,
  SILENT_E: /[^l]e$/,
  SILENT_ED: /(?:[^td]|^)ed$/,
  SILENT_ES: /[^sz]es$/,
  SUBTRACT:
    /(?:cial|tia|cius|cious|giu|ion|iou|sia$|[^aeiouy]eo|[aeiouy]ing$|[^aeiouy]y[aeiouy]|eous$|gue$|que$|[aeiou]{2}|[aeiou](?:re|le|les|ed|es|est|eth|ist|ism|ize|ous|ship|tion|tive|ture|ure|ward|wise|yer|ying)$)/g,
  VOWELS: /[aeiouy]+/g,
} as const;

const BIONIC_SYLLABLE_EXCEPTIONS = new Map<string, number>([
  ["business", 2],
  ["camera", 3],
  ["chocolate", 3],
  ["comfortable", 3],
  ["different", 2],
  ["evening", 2],
  ["every", 2],
  ["family", 3],
  ["favorite", 3],
  ["general", 3],
  ["interest", 3],
  ["interesting", 3],
  ["jewelry", 3],
  ["literature", 3],
  ["memory", 3],
  ["naturally", 3],
  ["restaurant", 3],
  ["science", 2],
  ["several", 3],
  ["temperature", 4],
  ["vegetable", 4],
  ["wednesday", 2],
]);

const BIONIC_PREFIX_PATTERN =
  /^(?:un|de|re|pre|pro|in|en|em|dis|mis|sub|inter|super|trans|non|over|under|out|up|down|anti|auto|bi|co|contra|counter|extra|hyper|i[lr]|im|inter|mid|multi|post|semi|sub|super|tele|tri|ultra|uni)/;

const BIONIC_COMMON_WORDS = new Set<string>([
  "the",
  "be",
  "of",
  "and",
  "to",
  "a",
  "in",
  "have",
  "it",
  "you",
  "for",
  "not",
  "that",
  "on",
  "with",
  "do",
  "as",
  "he",
  "we",
  "this",
  "at",
  "they",
  "but",
  "from",
  "by",
  "will",
  "or",
  "his",
  "say",
  "go",
  "she",
  "so",
  "all",
  "about",
  "if",
  "one",
  "would",
  "can",
  "which",
  "there",
  "know",
  "more",
  "get",
  "who",
  "like",
  "when",
  "think",
  "make",
  "time",
  "see",
  "what",
  "up",
  "some",
  "other",
  "out",
  "good",
  "people",
  "year",
  "take",
  "no",
  "well",
  "because",
  "very",
  "just",
  "come",
  "could",
  "work",
  "use",
  "than",
  "now",
  "then",
  "also",
  "into",
  "only",
  "look",
  "want",
  "give",
  "first",
  "new",
  "way",
  "find",
  "over",
  "any",
  "after",
  "thing",
  "our",
  "still",
  "even",
  "back",
  "too",
  "mean",
  "may",
  "here",
  "many",
  "such",
  "last",
  "child",
  "tell",
  "really",
  "call",
  "before",
  "company",
  "through",
  "down",
  "show",
  "life",
  "man",
  "change",
  "place",
  "long",
  "between",
  "feel",
  "same",
  "lot",
  "great",
  "help",
  "where",
  "problem",
  "try",
  "leave",
  "number",
  "part",
  "start",
  "case",
  "turn",
  "each",
  "end",
  "world",
  "school",
  "might",
  "need",
  "home",
  "course",
  "house",
  "us",
  "move",
  "system",
  "provide",
  "small",
  "service",
  "around",
  "however",
  "again",
  "ask",
  "large",
  "group",
  "war",
  "off",
  "always",
  "write",
  "point",
  "mother",
  "father",
  "question",
  "late",
  "night",
  "live",
  "run",
  "car",
  "set",
  "water",
  "area",
  "money",
  "name",
  "book",
  "both",
  "own",
  "read",
  "less",
  "friend",
  "month",
  "city",
  "business",
  "value",
  "side",
  "social",
  "story",
  "young",
  "fact",
  "lot",
  "study",
  "eye",
  "job",
  "word",
  "though",
  "issue",
  "kind",
  "four",
  "head",
  "far",
  "black",
  "long",
  "both",
  "little",
  "house",
  "yes",
  "since",
  "provide",
  "service",
  "around",
  "friend",
  "important",
  "father",
  "sit",
  "away",
  "until",
  "power",
  "hour",
  "game",
  "often",
  "yet",
  "line",
  "political",
  "end",
  "among",
  "ever",
  "stand",
  "bad",
  "lose",
  "however",
  "member",
  "pay",
  "law",
  "meet",
  "car",
  "city",
  "almost",
  "include",
  "continue",
  "set",
  "later",
  "community",
  "much",
  "name",
  "five",
  "once",
  "white",
  "least",
  "president",
  "learn",
  "real",
  "change",
  "team",
  "minute",
  "best",
  "several",
  "idea",
  "kid",
  "body",
  "information",
  "nothing",
  "ago",
  "right",
  "lead",
  "social",
  "understand",
  "whether",
  "watch",
  "together",
  "follow",
  "parent",
  "stop",
  "face",
  "anything",
  "create",
  "public",
  "already",
  "speak",
  "others",
  "office",
  "three",
  "room",
  "national",
  "point",
  "hold",
  "keep",
  "next",
  "hear",
  "example",
  "question",
  "during",
  "work",
  "play",
  "government",
  "run",
  "small",
  "number",
  "off",
  "always",
  "move",
  "night",
  "live",
  "Mr",
  "bring",
  "without",
  "before",
  "large",
  "million",
  "must",
  "home",
  "under",
  "water",
  "room",
  "write",
  "mother",
  "area",
  "national",
  "money",
  "story",
  "young",
  "fact",
  "month",
  "different",
  "lot",
]);

const DOM_SELECTORS = {
  ELEMENT_CHECKS: {
    [ElementCheckType.Editable]: {
      ATTRIBUTE_VALUES: [
        ["contenteditable", "true"],
        ["contenteditable", "plaintext-only"],
        ["contenteditable", ""],
      ],
      ATTRIBUTES: ["ng-model", "v-model", "data-reactroot"],
      CLASS_NAMES: [
        "editable",
        "editor",
        "wysiwyg",
        "rich-text",
        "quill",
        "monaco-editor",
        "CodeMirror",
        "ace_editor",
        "ql-editor",
        "tox-tinymce",
        "cke_editable",
      ],
      ROLES: [
        "combobox",
        "progressbar",
        "scrollbar",
        "searchbox",
        "slider",
        "spinbutton",
        "textbox",
      ],
      STYLES: [
        ["cursor", "text"],
        ["cursor", "text !important"],
      ],
      TAGS: ["INPUT", "TEXTAREA", "SELECT", "BUTTON", "OPTION"],
    },
    [ElementCheckType.Hidden]: {
      ATTRIBUTE_VALUES: [
        ["aria-hidden", "true"],
        ["aria-hidden", ""],
      ],
      CLASS_NAMES: ["code", "math", "syntax"],
      STYLES: [
        ["display", "none"],
        ["visibility", "hidden"],
        ["opacity", "0"],
        ["clipPath", "inset(100%)"],
        ["clip", "rect(0, 0, 0, 0)"],
      ],
    },
    [ElementCheckType.HighPerformance]: {
      ATTRIBUTES: [
        "data-player",
        "data-unity",
        "data-phaser",
        "data-visualization",
      ],
      CLASS_NAMES: [
        "video",
        "video-js",
        "plyr",
        "three-js",
        "webgl",
        "gsap-marker-root",
        "lottie",
        "unity",
        "phaser",
        "highcharts-container",
        "echarts",
        "visualization",
      ],
      TAGS: ["CANVAS", "OBJECT", "EMBED"],
    },
    [ElementCheckType.Ignored]: {
      TAGS: [
        "SCRIPT",
        "STYLE",
        "CODE",
        "PRE",
        "TEXTAREA",
        "INPUT",
        "NOSCRIPT",
        "CANVAS",
        "SVG",
        "IFRAME",
        "IMG",
        "VIDEO",
        "AUDIO",
        "OBJECT",
        "EMBED",
        "MAP",
        "FIGURE",
        "MATH",
        "SELECT",
        "OPTION",
        "BUTTON",
        "METER",
        "PROGRESS",
        "TIME",
        "OUTPUT",
        "TEMPLATE",
        "SLOT",
        "PORTAL",
        "DATALIST",
        "OPTGROUP",
        "MARQUEE",
        "EDITOR",
        "WYSIWYG",
        "DETAILS",
        "SUMMARY",
        "MENU",
        "MENUITEM",
        "TRACK",
        "SOURCE",
        "PICTURE",
        "HEAD",
        "LINK",
        "META",
        "BASE",
        "TITLE",
        "PATH",
        "CIRCLE",
        "RECT",
        "LINE",
        "POLYGON",
        "MTEXT",
        "MI",
        "MO",
        "MN",
        "ROUTER-VIEW",
        "ROUTER-LINK",
      ],
      CLASS_NAMES: ["button", "icon", "logo", "badge", "avatar", "spinner"],
    },
  },
} as const;

const BIONIC: BionicConfig = {
  boldCommonWords: false,
  boldFactor: 1,
  boldSingleSyllables: false,
  commonWords: BIONIC_COMMON_WORDS,
  MAX_BOLD_LENGTH: Math.min(5, Math.ceil(screenWidth / 200)),
  MIN_BOLD_LENGTH: 1,
  PREFIX_PATTERN: BIONIC_PREFIX_PATTERN,
  RATIOS: BIONIC_RATIOS,
  SYLLABLE_PATTERNS: BIONIC_SYLLABLE_PATTERNS,
  syllableExceptions: BIONIC_SYLLABLE_EXCEPTIONS,
} as const;

export const PROCESSOR_CONFIG: ProcessorConfig = {
  BIONIC,
  COLUMN_THRESHOLD: Math.max(50, Math.min(200, Math.floor(screenWidth * 0.1))),
  DOM_SELECTORS,
  ELEMENTS_PER_FRAME: isMobile ? 10 : 20,
  INTERSECTION_MARGIN: `${Math.floor(screenHeight * 0.2)}px`,
  INTERSECTION_THRESHOLD: isMobile ? 0.1 : 0.05,
  MUTATION,
  VIEWPORT_MARGIN: Math.max(100, Math.min(400, Math.floor(screenHeight * 0.5))),
} as const;
